spring.datasource.url=jdbc:postgresql://ep-small-poetry-aoqxxklw-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&prepareThreshold=0
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7i0dWIounvkt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080